"""add hashed_password to users

Revision ID: ea91ebd477e7
Revises: e40c73800a91
Create Date: 2025-12-11 03:00:11.318658

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea91ebd477e7'
down_revision: Union[str, None] = 'e40c73800a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('hashed_password', sa.String(length=255), nullable=False)
    )
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'password', sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
